version: 2
updates:
  
  # 1. Verifica as dependências Python (do seu pyproject.toml)
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "pip"
      include: "scope"

  # 2. Verifica as GitHub Actions (do seu .github/workflows)
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "actions"
      include: "scope"
