# Generated by Django 5.2.1 on 2025-05-28 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("certifiers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Certification",
            fields=[
                (
                    "id",
                    models.CharField(max_length=7, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
                ("examCode", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "durantion",
                    models.PositiveIntegerField(blank=True, default=0, null=True),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("idle", models.BooleanField(default=False)),
                (
                    "certifier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="certifiers.certifier",
                    ),
                ),
            ],
            options={
                "db_table": "tb_certification",
            },
        ),
    ]
