# Generated by Django 5.2.1 on 2025-05-28 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("certifications", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="certification",
            old_name="durantion",
            new_name="duration",
        ),
    ]
