# Generated by Django 5.2.1 on 2025-05-28 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Certifier",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("abbreviation", models.CharField(max_length=3, unique=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("idle", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "tb_certifier",
            },
        ),
    ]
